# Generated by Django 3.2.3 on 2022-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlemanage',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='idlemanage',
            name='wechat',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信号'),
        ),
    ]
