# Generated by Django 3.2.3 on 2022-02-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle', '0002_auto_20220203_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlemanage',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
