# Generated by Django 3.1 on 2021-11-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64, verbose_name='用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
                ('lasted_time', models.DateTimeField(auto_now=True, help_text='最后一次更新的时间', verbose_name='最后一次更新的时间')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'user_manage',
            },
        ),
    ]
