# Generated by Django 3.1 on 2021-11-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='username',
        ),
        migrations.AddField(
            model_name='usermanage',
            name='avatar_url',
            field=models.TextField(default='', verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='gender',
            field=models.IntegerField(choices=[('0', 'unknown'), ('1', '男'), ('2', '女')], default='0', verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='nickname',
            field=models.CharField(default='', max_length=64, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='openid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='openId'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='省份'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='session_key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='session_key'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='uid',
            field=models.CharField(default='2pk0s7v1f99', max_length=16, verbose_name='用户对外的ID'),
        ),
        migrations.AddField(
            model_name='usermanage',
            name='unionid',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='unionId'),
        ),
    ]
