# Generated by Django 3.1 on 2021-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0002_auto_20211103_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='3s3sw84pms5', max_length=16, verbose_name='用户对外的ID')),
            ],
            options={
                'verbose_name': '用户资产管理',
                'verbose_name_plural': '用户资产管理',
                'db_table': 'asset_manage',
            },
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='uid',
            field=models.CharField(default='3kjijqw3yi5', max_length=16, verbose_name='用户对外的ID'),
        ),
    ]
