# Generated by Django 3.1 on 2021-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0004_auto_20211105_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='uid',
            field=models.CharField(default='', max_length=16, verbose_name='用户对外ID'),
        ),
    ]
