# Generated by Django 3.1 on 2021-11-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0007_auto_20211121_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmanage',
            name='held_assets',
        ),
        migrations.AddField(
            model_name='assetmanage',
            name='day_asset',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='当日总资产'),
        ),
        migrations.AddField(
            model_name='assetmanage',
            name='day_pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=13, verbose_name='当日盈亏'),
        ),
    ]
