# Generated by Django 3.1 on 2021-11-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0008_auto_20211121_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmanage',
            name='create_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
    ]
