# Generated by Django 3.2.3 on 2021-12-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0011_alter_schusermanage_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schusermanage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='schusermanage',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='schusermanage',
            name='province',
        ),
    ]
