# Generated by Django 3.2.3 on 2021-12-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0013_alter_schusermanage_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schusermanage',
            name='authenticate_status',
            field=models.CharField(choices=[('0', 'unknown'), ('1', '未认证'), ('2', '人工审核中'), ('3', '已认证'), ('4', '认证失败')], default='0', max_length=8, verbose_name='认证状态'),
        ),
    ]
