# Generated by Django 3.2.3 on 2021-12-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0014_schusermanage_authenticate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schusermanage',
            name='school_card',
            field=models.TextField(default='', verbose_name='校卡图片地址'),
        ),
    ]
