# Generated by Django 3.2.3 on 2021-12-27 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0017_alter_schusermanage_school_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schusermanage',
            name='school_card',
            field=models.TextField(blank=True, default='', null=True, verbose_name='校卡图片地址'),
        ),
    ]
