# Generated by Django 3.2.3 on 2021-12-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0018_alter_schusermanage_school_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='schusermanage',
            name='test_field',
            field=models.TextField(blank=True, null=True, verbose_name='测试'),
        ),
    ]
