# Generated by Django 3.2.3 on 2021-12-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0019_schusermanage_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schusermanage',
            name='test_field',
        ),
    ]
