# Generated by Django 3.2.3 on 2022-01-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0020_remove_schusermanage_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='province',
        ),
    ]
