# Generated by Django 3.2.3 on 2022-01-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0021_auto_20220102_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schusermanage',
            name='school_card',
        ),
        migrations.AlterField(
            model_name='schusermanage',
            name='authenticate_status',
            field=models.CharField(choices=[('0', '用户未使用小程序'), ('1', '未授权定位信息'), ('2', '已采集第一次定位信息'), ('3', '本校用户'), ('4', '非本校用户'), ('5', '人工审核')], default='0', max_length=8, verbose_name='认证状态'),
        ),
    ]
