# Generated by Django 3.2.3 on 2022-01-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0023_alter_schusermanage_authenticate_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetmanage',
            options={'verbose_name': '可转债用户资产管理', 'verbose_name_plural': '可转债用户资产管理'},
        ),
        migrations.AlterModelOptions(
            name='usermanage',
            options={'verbose_name': '可转债用户管理', 'verbose_name_plural': '可转债用户管理'},
        ),
    ]
