# Generated by Django 3.2.3 on 2022-01-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0024_auto_20220123_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schusermanage',
            name='authenticate_status',
            field=models.CharField(choices=[('0', '用户第一次使用小程序'), ('1', '未授权定位信息'), ('2', '已采集第一次定位信息'), ('3', '人工审核'), ('4', '非本校用户'), ('5', '本校用户')], default='0', max_length=8, verbose_name='认证状态'),
        ),
    ]
