# Generated by Django 3.1 on 2021-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, verbose_name='用户对外ID')),
                ('day_asset', models.FloatField(default=0, verbose_name='当日资产')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '日资金表',
                'verbose_name_plural': '日资金表',
                'db_table': 'day_fund',
            },
        ),
        migrations.CreateModel(
            name='DayProfitLossConvertBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, verbose_name='用户对外ID')),
                ('convert_id', models.IntegerField(verbose_name='可转债ID')),
                ('bond_abbr', models.CharField(max_length=256, verbose_name='债券简称')),
                ('bond_code', models.CharField(max_length=256, verbose_name='债券代码')),
                ('quote_change', models.FloatField(default=0, verbose_name='涨跌幅')),
                ('pre_day_fund', models.FloatField(default=0, verbose_name='昨日总资金')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '可转债日盈亏表',
                'verbose_name_plural': '可转债日盈亏表',
                'db_table': 'day_profit_loss_convert_bond',
            },
        ),
        migrations.CreateModel(
            name='OwnConvertBond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, verbose_name='用户对外ID')),
                ('bond_abbr', models.CharField(max_length=256, verbose_name='债券简称')),
                ('bond_code', models.CharField(max_length=256, verbose_name='债券代码')),
                ('hold_status', models.CharField(choices=[('held', '已持有'), ('chosen', '已选择')], default='chosen', max_length=16, verbose_name='持有状态')),
                ('hold_num', models.IntegerField(default=0, verbose_name='持有数量')),
                ('cost', models.FloatField(default=0, verbose_name='成本')),
                ('priority', models.IntegerField(default=0, verbose_name='显示的优先级')),
                ('option_time', models.CharField(default='', max_length=64, verbose_name='自选时间(字符串存储)')),
                ('hold_time', models.CharField(default='', max_length=64, verbose_name='持有时间(字符串存储)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自有可转债管理',
                'verbose_name_plural': '自有可转债管理',
                'db_table': 'own_convert_bond',
            },
        ),
    ]
