# Generated by Django 3.1 on 2021-11-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownconvertbond',
            old_name='option_time',
            new_name='chosen_time',
        ),
        migrations.RenameField(
            model_name='ownconvertbond',
            old_name='hold_time',
            new_name='held_time',
        ),
    ]
