# Generated by Django 3.1 on 2021-11-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0002_auto_20211109_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownconvertbond',
            name='cost',
        ),
        migrations.AddField(
            model_name='ownconvertbond',
            name='hold_cost',
            field=models.FloatField(default=0, verbose_name='持有成本'),
        ),
    ]
