# Generated by Django 3.1 on 2021-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0003_auto_20211111_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfChooseManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, verbose_name='用户对外ID')),
                ('bond_abbr', models.CharField(max_length=256, verbose_name='债券简称')),
                ('bond_code', models.CharField(max_length=256, verbose_name='债券代码')),
                ('priority', models.IntegerField(default=0, verbose_name='显示的优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自选管理',
                'verbose_name_plural': '自选管理',
                'db_table': 'self_choose_manage',
            },
        ),
        migrations.RemoveField(
            model_name='ownconvertbond',
            name='chosen_time',
        ),
        migrations.RemoveField(
            model_name='ownconvertbond',
            name='held_time',
        ),
        migrations.RemoveField(
            model_name='ownconvertbond',
            name='hold_status',
        ),
    ]
