# Generated by Django 3.1 on 2021-11-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0004_auto_20211111_0120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownconvertbond',
            options={'verbose_name': '持有可转债', 'verbose_name_plural': '持有可转债'},
        ),
        migrations.AlterModelOptions(
            name='selfchoosemanage',
            options={'verbose_name': '自选可转债', 'verbose_name_plural': '自选可转债'},
        ),
    ]
