# Generated by Django 3.1 on 2021-11-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0005_auto_20211111_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayfund',
            options={'verbose_name': '日资金流记录', 'verbose_name_plural': '日资金流记录'},
        ),
        migrations.AlterModelOptions(
            name='dayprofitlossconvertbond',
            options={'verbose_name': '可转债日盈亏记录', 'verbose_name_plural': '可转债日盈亏记录'},
        ),
    ]
