# Generated by Django 3.1 on 2021-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0006_auto_20211111_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayprofitlossconvertbond',
            name='create_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
    ]
