# Generated by Django 3.1 on 2021-11-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0007_auto_20211122_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayFund',
        ),
    ]
