# Generated by Django 3.1 on 2021-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0008_delete_dayfund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownconvertbond',
            name='hold_cost',
            field=models.FloatField(verbose_name='持有成本'),
        ),
        migrations.AlterField(
            model_name='ownconvertbond',
            name='hold_num',
            field=models.IntegerField(verbose_name='持有数量'),
        ),
    ]
