# Generated by Django 3.1 on 2021-11-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0009_auto_20211124_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayprofitlossconvertbond',
            name='convert_id',
        ),
    ]
