# Generated by Django 3.1 on 2021-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bond_manage', '0010_remove_dayprofitlossconvertbond_convert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayprofitlossconvertbond',
            name='pre_day_fund',
        ),
        migrations.RemoveField(
            model_name='dayprofitlossconvertbond',
            name='quote_change',
        ),
        migrations.AddField(
            model_name='dayprofitlossconvertbond',
            name='day_pl',
            field=models.FloatField(default=0, verbose_name='当日盈亏'),
        ),
        migrations.AddField(
            model_name='dayprofitlossconvertbond',
            name='day_quote_change',
            field=models.FloatField(default=0, verbose_name='当日涨跌幅'),
        ),
    ]
