# Generated by Django 3.2.3 on 2022-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='用户昵称')),
                ('avatar_url', models.TextField(default='', verbose_name='用户头像地址')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, max_length=128, null=True, verbose_name='微信号')),
                ('content', models.TextField(default='', verbose_name='互助描述')),
                ('salary', models.IntegerField(default=0, verbose_name='价格')),
                ('mut_type', models.CharField(choices=[('0', 'unknown'), ('1', '代拿快递'), ('2', '代拿外卖'), ('3', '寻物启事'), ('4', '失物招领'), ('5', '其他互助')], db_index=True, default='0', max_length=8, verbose_name='互助类型')),
                ('school', models.CharField(choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学'), ('11', '深圳技师学院')], db_index=True, default='0', max_length=8, verbose_name='学校')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('img_paths', models.TextField(default='', verbose_name='图片路由')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '互助管理',
                'verbose_name_plural': '互助管理',
                'db_table': 'mutual',
            },
        ),
    ]
