# Generated by Django 3.2.3 on 2022-02-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_aid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualmanage',
            name='mut_type',
            field=models.CharField(choices=[('0', 'unknown'), ('1', '代拿快递'), ('2', '代拿外卖'), ('3', '寻物启事'), ('4', '失物招领'), ('5', '其他')], db_index=True, default='0', max_length=8, verbose_name='互助类型'),
        ),
    ]
