# Generated by Django 3.2.3 on 2021-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='用户昵称')),
                ('mood_id', models.IntegerField(default=0, verbose_name='帖子ID')),
                ('content', models.CharField(default='', max_length=256, verbose_name='评论内容')),
                ('is_sec_comment', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否二级评论')),
                ('fir_comment_uid', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='一级评论ID')),
                ('fir_comment_nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户昵称')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
                'db_table': 'comment_manage',
            },
        ),
        migrations.CreateModel(
            name='TopicManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='用户昵称')),
                ('avatar_url', models.TextField(default='', verbose_name='用户头像地址')),
                ('title', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='帖子标题')),
                ('content', models.CharField(default='', max_length=512, verbose_name='帖子内容')),
                ('topic_type', models.CharField(blank=True, choices=[('0', 'unknown'), ('1', 'mood'), ('2', 'confession'), ('3', 'sellmate')], default='0', max_length=8, null=True, verbose_name='帖子类型')),
                ('school', models.CharField(blank=True, choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学')], db_index=True, default='0', max_length=8, null=True, verbose_name='学校')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('img_paths', models.TextField(default='', verbose_name='图片路由')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '帖子管理',
                'verbose_name_plural': '帖子管理',
                'db_table': 'topic_manage',
            },
        ),
    ]
