# Generated by Django 3.2.3 on 2021-12-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmanage',
            old_name='mood_id',
            new_name='inst_id',
        ),
    ]
