# Generated by Django 3.2.3 on 2021-12-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0002_rename_mood_id_commentmanage_inst_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmanage',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='创建的时间', verbose_name='创建的时间'),
        ),
    ]
