# Generated by Django 3.2.3 on 2021-12-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0005_alter_topicmanage_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmanage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间'),
        ),
    ]
