# Generated by Django 3.2.3 on 2022-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0009_topicmanage_view_uids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmanage',
            name='content',
            field=models.TextField(default='', verbose_name='帖子内容'),
        ),
        migrations.AlterField(
            model_name='topicmanage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='帖子标题'),
        ),
    ]
