# Generated by Django 3.2.3 on 2022-01-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0010_auto_20220130_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmanage',
            name='content',
            field=models.CharField(default='', max_length=1024, verbose_name='评论内容'),
        ),
    ]
