# Generated by Django 3.2.3 on 2022-02-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0011_alter_commentmanage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicmanage',
            name='view_uids',
        ),
        migrations.AddField(
            model_name='topicmanage',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='topicmanage',
            name='liker_ids',
            field=models.TextField(blank=True, help_text='浏览用户的id(避免uid占用过带宽)', null=True, verbose_name='点赞用户的id'),
        ),
        migrations.AddField(
            model_name='topicmanage',
            name='view_ids',
            field=models.TextField(blank=True, help_text='浏览用户的id(避免uid占用过带宽)', null=True, verbose_name='浏览用户的id'),
        ),
    ]
