# Generated by Django 3.2.3 on 2022-02-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0013_auto_20220218_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmanage',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
