# Generated by Django 3.2.3 on 2022-02-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_manage', '0015_alter_topicmanage_topic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmanage',
            name='deleter_uid',
            field=models.CharField(default='', max_length=16, verbose_name='下架该数据的uid'),
        ),
    ]
