# Generated by Django 3.1 on 2021-11-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_code', models.CharField(default='', max_length=256, verbose_name='债券代码')),
                ('bond_abbr', models.CharField(default='', max_length=256, verbose_name='债券简称')),
                ('purchase_date', models.CharField(default='', max_length=256, verbose_name='申购日期')),
                ('purchase_code', models.CharField(default='', max_length=256, verbose_name='申购代码')),
                ('purchase_limit', models.CharField(default='', max_length=256, verbose_name='申购上限')),
                ('underly_code', models.CharField(default='', max_length=256, verbose_name='正股代码')),
                ('underly_abbr', models.CharField(default='', max_length=256, verbose_name='正股简称')),
                ('underly_price', models.CharField(default='', max_length=256, verbose_name='正股价')),
                ('conversion_price', models.CharField(default='', max_length=256, verbose_name='转股价')),
                ('conversion_value', models.CharField(default='', max_length=256, verbose_name='转股价值')),
                ('cur_bond_price', models.CharField(default='', max_length=256, verbose_name='债现价')),
                ('conversion_preminum_rate', models.CharField(default='', max_length=256, verbose_name='转股溢价率')),
                ('abos_erd', models.CharField(default='', max_length=256, verbose_name='原股东配售-股权登记日')),
                ('abos_aps', models.CharField(default='', max_length=256, verbose_name='原股东配售-每股配售额')),
                ('issurance_scale', models.CharField(default='', max_length=256, verbose_name='发行规模')),
                ('ido_wln', models.CharField(default='', max_length=256, verbose_name='中签号发布日')),
                ('win_rate', models.CharField(default='', max_length=256, verbose_name='中签率')),
                ('time_market', models.CharField(default='', max_length=256, verbose_name='上市时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lasted_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '基础可转债信息表',
                'verbose_name_plural': '基础可转债信息表',
                'db_table': 'base_convert',
            },
        ),
    ]
