# Generated by Django 3.1 on 2021-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconvert',
            name='yes_close_price',
            field=models.CharField(default='', max_length=256, verbose_name='昨日收盘价'),
        ),
    ]
