# Generated by Django 3.1 on 2021-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='用户昵称')),
                ('avatar_url', models.TextField(default='', verbose_name='用户头像地址')),
                ('title', models.CharField(default='', help_text='物品名称', max_length=32, verbose_name='物品名称')),
                ('description', models.CharField(default='', help_text='物品描述', max_length=512, verbose_name='物品描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '帖子管理',
                'verbose_name_plural': '帖子管理',
                'db_table': 'mood_manage',
            },
        ),
    ]
