# Generated by Django 3.1 on 2021-12-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodmanage',
            name='description',
        ),
        migrations.AddField(
            model_name='moodmanage',
            name='content',
            field=models.CharField(default='', max_length=512, verbose_name='帖子内容'),
        ),
        migrations.AlterField(
            model_name='moodmanage',
            name='title',
            field=models.CharField(default='', max_length=32, verbose_name='帖子标题'),
        ),
    ]
