# Generated by Django 3.1 on 2021-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0002_auto_20211205_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodmanage',
            name='img_paths',
            field=models.TextField(default='', verbose_name='图片路由'),
        ),
    ]
