# Generated by Django 3.1 on 2021-12-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0003_moodmanage_img_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodmanage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='帖子标题'),
        ),
    ]
