# Generated by Django 3.1 on 2021-12-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0004_auto_20211205_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodmanage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
