# Generated by Django 3.1 on 2021-12-07 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0005_moodmanage_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='用户昵称')),
                ('mood_id', models.IntegerField(default=0, verbose_name='帖子ID')),
                ('content', models.CharField(default='', max_length=256, verbose_name='评论内容')),
                ('is_sec_comment', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否二级评论')),
                ('fir_comment_uid', models.IntegerField(blank=True, null=True, verbose_name='一级评论ID')),
                ('fir_comment_nickname', models.CharField(blank=True, max_length=32, null=True, verbose_name='用户昵称')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '评论管理',
                'verbose_name_plural': '评论管理',
                'db_table': 'comment_manage',
            },
        ),
        migrations.AddField(
            model_name='moodmanage',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
