# Generated by Django 3.1 on 2021-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0006_auto_20211207_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmanage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
