# Generated by Django 3.1 on 2021-12-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_manage', '0007_commentmanage_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmanage',
            name='fir_comment_uid',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='一级评论ID'),
        ),
    ]
