# Generated by Django 3.1 on 2021-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdleManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=32, verbose_name='卖家昵称')),
                ('avatar_url', models.TextField(default='', verbose_name='卖家头像地址')),
                ('wechat', models.CharField(default='', max_length=128, verbose_name='卖家微信')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='卖家手机号')),
                ('title', models.CharField(default='', help_text='物品名称', max_length=32, verbose_name='物品名称')),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, help_text='售价', max_digits=10, verbose_name='售价')),
                ('description', models.CharField(default='', help_text='物品描述', max_length=512, verbose_name='物品描述')),
                ('order_status', models.CharField(choices=[('1', '售卖中'), ('2', '已完成'), ('3', '已取消')], default='1', help_text='订单状态', max_length=8, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建的时间', verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '闲置管理',
                'verbose_name_plural': '闲置管理',
                'db_table': 'idle_manage',
            },
        ),
    ]
