# Generated by Django 3.1 on 2021-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlemanage',
            name='img_paths',
            field=models.TextField(default='', verbose_name='图片路由'),
        ),
    ]
