# Generated by Django 3.1 on 2021-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle_manage', '0002_idlemanage_img_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idlemanage',
            name='order_status',
            field=models.CharField(choices=[('1', '售卖中'), ('2', '已完成'), ('3', '已下架')], default='1', help_text='订单状态', max_length=8, verbose_name='订单状态'),
        ),
    ]
