# Generated by Django 3.1 on 2021-12-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idle_manage', '0003_auto_20211206_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='idlemanage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
