# Generated by Django 3.1 on 2021-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZsdxUserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('nickname', models.CharField(default='', max_length=64, verbose_name='昵称')),
                ('avatar_url', models.TextField(default='', verbose_name='头像地址')),
                ('wechat', models.CharField(default='', max_length=128, verbose_name='微信')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('unionid', models.CharField(blank=True, max_length=256, null=True, verbose_name='unionId')),
                ('openid', models.CharField(blank=True, max_length=256, null=True, verbose_name='openId')),
                ('session_key', models.CharField(blank=True, max_length=256, null=True, verbose_name='session_key')),
                ('gender', models.CharField(choices=[('0', 'unknown'), ('1', '男'), ('2', '女')], default='0', max_length=16, verbose_name='性别')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=64, null=True, verbose_name='省份')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lasted_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '中山大学用户管理',
                'verbose_name_plural': '中山大学用户管理',
                'db_table': 'zsdx_user_manage',
            },
        ),
    ]
