# Generated by Django 3.1 on 2021-12-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zsdx_user_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zsdxusermanage',
            old_name='phone',
            new_name='mobile',
        ),
    ]
