# Generated by Django 3.1 on 2021-11-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=128, verbose_name='配置项名称')),
                ('uni_val', models.TextField(default='', verbose_name='唯一值配置项')),
                ('opt_val_one', models.CharField(choices=[('unknown', 'unknown'), ('open', 'open'), ('off', 'off')], default='unknown', max_length=64, verbose_name='可选值配置项一')),
                ('instruction', models.TextField(default='', verbose_name='说明')),
            ],
            options={
                'verbose_name': '配置管理',
                'verbose_name_plural': '配置管理',
                'db_table': 'configuration',
            },
        ),
    ]
