# Generated by Django 3.2.3 on 2021-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchSwiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学')], default='0', max_length=8, verbose_name='学校')),
                ('swiper_type', models.CharField(choices=[('1', '显示图片'), ('2', '显示推文'), ('3', '跳转小程序')], default='1', max_length=8, verbose_name='类型')),
                ('img_path', models.FileField(help_text='图片（ImageField）', upload_to='swiper', verbose_name='图片')),
                ('mp_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='小程序ID')),
                ('tweets_url', models.TextField(blank=True, null=True, verbose_name='推文链接')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
                'db_table': 'sch_swiper',
            },
        ),
    ]
