# Generated by Django 3.2.3 on 2021-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_manage', '0002_schswiper'),
    ]

    operations = [
        migrations.AddField(
            model_name='schswiper',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否下架'),
        ),
    ]
