# Generated by Django 3.2.3 on 2021-12-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_manage', '0003_schswiper_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schswiper',
            name='school',
            field=models.CharField(choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学'), ('11', '深圳技师学院')], default='0', max_length=8, verbose_name='学校'),
        ),
    ]
