# Generated by Django 3.2.3 on 2022-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job', '0002_auto_20220203_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmanage',
            name='job_name',
            field=models.CharField(default='', max_length=128, verbose_name='岗位名称'),
        ),
    ]
