# Generated by Django 3.2.3 on 2022-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_job', '0003_jobmanage_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmanage',
            name='job_type',
            field=models.CharField(choices=[('0', 'unknown'), ('1', '兼职'), ('2', '实习'), ('3', '校招')], db_index=True, default='0', max_length=8, verbose_name='工作类型'),
        ),
    ]
