# Generated by Django 3.1 on 2021-12-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_type', models.CharField(choices=[('0', 'unknown'), ('1', 'idle'), ('2', 'mood')], db_index=True, default='0', max_length=4, verbose_name='图片类型')),
                ('inst_id', models.IntegerField(default=0, verbose_name='类型实例ID')),
                ('file_path', models.FileField(blank=True, help_text='图片（ImageField）', null=True, upload_to='photos/', verbose_name='图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '图片文件',
                'verbose_name_plural': '图片文件',
                'db_table': 'image_file',
            },
        ),
    ]
