# Generated by Django 3.1 on 2021-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='inst_type',
            field=models.CharField(choices=[('0', 'unknown'), ('1', 'idle'), ('2', 'mood'), ('3', 'swiper')], db_index=True, default='0', max_length=4, verbose_name='图片类型'),
        ),
    ]
