# Generated by Django 3.2.3 on 2021-12-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0002_auto_20211207_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='inst_type',
            field=models.CharField(choices=[('0', 'unknown'), ('1', 'idle'), ('2', 'mood'), ('3', 'swiper'), ('4', 'confession_wall'), ('5', 'sell_roommate')], db_index=True, default='0', max_length=4, verbose_name='图片类型'),
        ),
    ]
