# Generated by Django 3.2.3 on 2021-12-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0003_alter_imagefile_inst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='school',
            field=models.CharField(blank=True, choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学')], db_index=True, default='0', max_length=8, null=True, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='inst_type',
            field=models.CharField(choices=[('0', 'unknown'), ('1', 'idle'), ('2', 'mood'), ('3', 'confession_wall'), ('4', 'sell_roommate'), ('5', 'swiper')], db_index=True, default='0', max_length=4, verbose_name='图片类型'),
        ),
    ]
