# Generated by Django 3.2.3 on 2021-12-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0008_alter_imagefile_inst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='inst_id',
            field=models.CharField(default='0', max_length=128, verbose_name='类型实例ID'),
        ),
    ]
