# Generated by Django 3.2.3 on 2021-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0009_alter_imagefile_inst_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file_path',
            field=models.FileField(blank=True, help_text='图片（ImageField）', null=True, upload_to='photos/2021-12-21', verbose_name='图片'),
        ),
    ]
