# Generated by Django 3.2.3 on 2022-01-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0024_alter_imagefile_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('audio_path', models.FileField(upload_to='audios/2022-01-17', verbose_name='音频地址')),
                ('duration', models.IntegerField(verbose_name='音频时长')),
                ('size', models.IntegerField(verbose_name='音频大小')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '音频管理',
                'verbose_name_plural': '音频管理',
                'db_table': 'audio_file',
            },
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='file_path',
            field=models.FileField(blank=True, help_text='图片（ImageField）', null=True, upload_to='photos/2022-01-17', verbose_name='图片'),
        ),
    ]
