# Generated by Django 3.2.3 on 2022-01-17 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manage', '0025_auto_20220117_0015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
    ]
