# Generated by Django 3.2.3 on 2022-01-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=16, verbose_name='用户对外ID')),
                ('school', models.CharField(blank=True, choices=[('0', 'unknown'), ('1', '深圳大学'), ('2', '暨南大学深圳校区'), ('3', '南方科技大学'), ('4', '哈尔滨工业大学'), ('5', '香港中文大学'), ('6', '深圳职业技术学院'), ('7', '深圳信息职业技术学院'), ('8', '中山大学'), ('9', '深圳理工大学'), ('10', '北理莫斯科大学'), ('11', '深圳技师学院')], default='0', max_length=8, null=True, verbose_name='学校')),
                ('latitude', models.CharField(default='', max_length=32, verbose_name='纬度')),
                ('longitude', models.CharField(default='', max_length=32, verbose_name='经度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '高校用户定位数据管理',
                'verbose_name_plural': '高校用户定位数据管理',
                'db_table': 'sch_location',
            },
        ),
    ]
