# Generated by Django 3.2.3 on 2022-01-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_user_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='sta_dist_one',
            field=models.IntegerField(default=-1, verbose_name='与标准位置一的距离(m)'),
        ),
        migrations.AddField(
            model_name='location',
            name='sta_dist_two',
            field=models.IntegerField(default=-1, verbose_name='与标准位置二的距离(m)'),
        ),
    ]
